-- MySQL Script generated by MySQL Workbench
-- Monday 01 June 2020 02:52:58 PM
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema libera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libera` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `libera` ;

-- -----------------------------------------------------
-- Table `libera`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`authors` (
  `author_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`publishers` (
  `publisher_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`books` (
  `book_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `author_id` SMALLINT UNSIGNED NOT NULL,
  `publisher_id` TINYINT UNSIGNED NOT NULL,
  `year_published` YEAR NOT NULL,
  `total_copies` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`book_id`),
  UNIQUE INDEX `book_id_UNIQUE` (`book_id` ASC) VISIBLE,
  INDEX `fk_books_authors_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_books_publishers1_idx` (`publisher_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors`
    FOREIGN KEY (`author_id`)
    REFERENCES `libera`.`authors` (`author_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_books_publishers`
    FOREIGN KEY (`publisher_id`)
    REFERENCES `libera`.`publishers` (`publisher_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`holdings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`holdings` (
  `holding_number` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_id` SMALLINT UNSIGNED NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`holding_number`),
  UNIQUE INDEX `holding_number_UNIQUE` (`holding_number` ASC) VISIBLE,
  INDEX `fk_holdings_books` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_holdings_books`
    FOREIGN KEY (`book_id`)
    REFERENCES `libera`.`books` (`book_id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 184
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`users` (
  `user_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(1024) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`issues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`issues` (
  `issue_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` SMALLINT UNSIGNED NOT NULL,
  `issued_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  PRIMARY KEY (`issue_id`),
  UNIQUE INDEX `issue_id_UNIQUE` (`issue_id` ASC) VISIBLE,
  INDEX `fk_issues_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_issues_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `libera`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`issue_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`issue_details` (
  `issue_id` SMALLINT UNSIGNED NOT NULL,
  `holding_number` SMALLINT UNSIGNED NOT NULL,
  `submission_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`issue_id`, `holding_number`),
  INDEX `fk_issue_details_issues1_idx` (`issue_id` ASC) VISIBLE,
  CONSTRAINT `fk_issue_details_issues`
    FOREIGN KEY (`issue_id`)
    REFERENCES `libera`.`issues` (`issue_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libera`.`librarians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`librarians` (
  `librarian_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(1024) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `is_admin` TINYINT NOT NULL,
  PRIMARY KEY (`librarian_id`),
  UNIQUE INDEX `librarian_id_UNIQUE` (`librarian_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `libera` ;

-- -----------------------------------------------------
-- Placeholder table for view `libera`.`book_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`book_details` (`book_id` INT, `title` INT, `author` INT, `publisher` INT, `year_published` INT, `total_copies` INT, `available_copies` INT);

-- -----------------------------------------------------
-- Placeholder table for view `libera`.`rented_books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libera`.`rented_books` (`book_id` INT, `count` INT);

-- -----------------------------------------------------
-- View `libera`.`book_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libera`.`book_details`;
USE `libera`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `libera`.`book_details` AS select `b`.`book_id` AS `book_id`,`b`.`title` AS `title`,concat(`a`.`first_name`,' ',`a`.`last_name`) AS `author`,`p`.`name` AS `publisher`,`b`.`year_published` AS `year_published`,`b`.`total_copies` AS `total_copies`,(`b`.`total_copies` - ifnull(`rb`.`count`,0)) AS `available_copies` from (((`libera`.`books` `b` join `libera`.`authors` `a` on((`b`.`author_id` = `a`.`author_id`))) join `libera`.`publishers` `p` on((`b`.`publisher_id` = `p`.`publisher_id`))) left join `libera`.`rented_books` `rb` on((`b`.`book_id` = `rb`.`book_id`))) order by `b`.`book_id`;

-- -----------------------------------------------------
-- View `libera`.`rented_books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `libera`.`rented_books`;
USE `libera`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `libera`.`rented_books` AS select `h`.`book_id` AS `book_id`,count(0) AS `count` from (`libera`.`issue_details` `id` join `libera`.`holdings` `h` on((`id`.`holding_number` = `h`.`holding_number`))) where (`id`.`submission_date` is null) group by `h`.`book_id`;
USE `libera`;

DELIMITER $$
USE `libera`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `libera`.`holdings_after_delete`
AFTER DELETE ON `libera`.`holdings`
FOR EACH ROW
BEGIN

    UPDATE books
    SET total_copies = total_copies - 1
    WHERE book_id = OLD.book_id;

END$$

USE `libera`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `libera`.`holdings_after_insert`
AFTER INSERT ON `libera`.`holdings`
FOR EACH ROW
BEGIN

    UPDATE books
    SET total_copies = total_copies + 1
    WHERE book_id = NEW.book_id;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Add Admin in 'librarians'
-- -----------------------------------------------------
INSERT INTO `libera`.`librarians` (first_name, last_name, email, password, phone, address, is_admin)
VALUES ('Ad', 'Min', 'admin@mail.com', '$2a$10$knih7H2.qYU84Xs/mLCEE.Jf2z.yL.p99c5MCsvx07Go/lBS6OhsG', '0123456789', 'HQ', 1);
